# Generated by Django 5.1.3 on 2024-12-31 11:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=255)),
                ('header_image', models.ImageField(blank=True, null=True, upload_to='client_headers/')),
                ('google_maps_link', models.URLField(blank=True, max_length=500, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=10, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('discount', models.FloatField(help_text='Discount in percentage')),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='coupon_image/')),
                ('submittd_by_user', models.BooleanField(default=False)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('shareable_link', models.URLField(blank=True, editable=False, max_length=500, null=True)),
                ('redeemed', models.BooleanField(default=False)),
                ('message', models.CharField(blank=True, max_length=500)),
                ('max_users', models.PositiveIntegerField(default=1)),
                ('used_count', models.PositiveIntegerField(default=0)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.client')),
            ],
        ),
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('whatsapp_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('coupon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.coupon')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
